Show worker name in connections RabbitMQ admin management
vyuldashev/laravel-queue-rabbitmq pull request #487
Opened 2022-10-17 11:49 UTC by i3bepb

In console command exist options worker name. I suggest using this name in connections RabbitMQ admin management.
```sh
./artisan rabbitmq:consume --name="Consumer RaSmartId"
```

Now it looks like this:

![Look bad](https://user-images.githubusercontent.com/1553797/196167651-aa9771d8-dda7-4480-b3db-0d94e83119c3.png "Look bad")

After change:

![Look good](https://user-images.githubusercontent.com/1553797/196169138-1637c7e8-9ba1-4594-851f-fa6ccdb34ae9.png "Look good")

https://github.com/php-amqplib/php-amqplib/issues/728

2023-01-01 12:38 UTC, everflux commented
Is there a reason not to user the AMQPConnectionConfig?
For example

```
 $config = new AMQPConnectionConfig();
 $config->setConnectionName("PHP-worker-node-1");
    $connection = new AMQPSSLConnection( 'localhost', 1234, 'guest',   'guest', '/', $ssl_options, array(), 'ssl', $config);
```

2023-01-01 20:00 UTC, i3bepb commented
@everflux 
> Is there a reason not to user the AMQPConnectionConfig? For example

The method ```setConnectionName``` was added only in [php-amqplib/php-amqplib](https://github.com/php-amqplib/php-amqplib) 3.4, before it was not. I suggested changes before the release 3.4.

Now yes it is correct to use method ```setConnectionName```

2023-01-25 19:43 UTC, khepin approved these changes

2023-01-25 22:50 UTC, M-Porter requested changes

2023-01-25 22:50 UTC, M-Porter commented on src/Consumer.php
> +        $phpAmqpLibConnection = $this->container['config']["queue.connections.$connectionName.connection"];
I think we'd want to only set the name if this config value is set.

I'm not sure everyone would like to see `\PhpAmqpLib\Connection\AMQPLazyConnection` start appearing by default as the connection name in the UI.

2023-06-15 16:19 UTC, M-Porter commented
Closing as resolved by https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/528

2023-06-15 16:19 UTC, closed without merging